### ISSUE TITLE
Interface enhancements

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/sce-domain-discovery#1]
Just a few things - should just be cosmetic and relatively simple

1. Change "Build Model" to "Create New Model"
2. Move the import and export model functionality to the left side bar underneath "Create New Model"

**Comment by giuseppetotaro** [comment]
I changed the name of the button and provided the function that effectively creates a new model if the user wants to build it from scratch and overwrites that one previously trained, if it exists (commits 02cb06022b08f44121fad0731ccaeac448361518 and e44af8d44a8aa8d3a06cc73f6ced3c69949b49aa).
