### ISSUE TITLE
Add Upload Seed File functionality

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/sce-domain-discovery#12]
For this first pass, it should accept a .txt file only and do some basic checking to make sure that the file contains useful urls.
The file should then be saved to the appropriate location on the server, and ideally the name of the file will be shown on the interface.

**Comment by giuseppetotaro** [comment]
Commit 2ac4eb1643bb8e8efc73e34fc8b3a94ffc7bde2b adds this functionality. We need to improve this by showing the seed file currently loaded.

**Comment by wmburke** [comment]
I've created a new issue for further improvements.  Let's call this one done.
