### ISSUE TITLE
Add Launch Crawl Button

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/sce-domain-discovery#13]
If there is a seed file and at least 10 of each type of relevancy marked, the crawl button should be usable. It will just launch the crawl.

**Comment by giuseppetotaro** [comment]
Commit 2ac4eb1643bb8e8efc73e34fc8b3a94ffc7bde2b adds this functionality. We just need to check if there is at least 10 of each type of relevancy marked.

**Comment by wmburke** [comment]
looks like you did this - I got a warning when trying to launch w/o 10 of each marked
