### ISSUE TITLE
Stop Crawl Button

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/sce-domain-discovery#15]
If we're going to launch a crawl that will run forever, we need a stop crawl button also.

**Comment by giuseppetotaro** [comment]
Commit 2ac4eb1643bb8e8efc73e34fc8b3a94ffc7bde2b adds this functionality. There are two buttos: "Stop Crawl" stops gracefully the crawl job and "Halt Crawl" forces the crawl job to be stopped. @wmburke please close this issue if it works for you.

**Comment by wmburke** [comment]
I like the distinction - we just need some hover tips so someone besides you and I can understand what the different is between the two. But I've added that in a general UI issue so we can close this one.
Thank you!
