### ISSUE TITLE
Make useful metrics

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/sce-domain-discovery#2]
Either make Accuracy mean something or replace it with something else useful, eg Number of Highly Relevant, Relevant, and Not Relevant pages that have been marked.

**Comment by giuseppetotaro** [comment]
Commit number 02cb06022b08f44121fad0731ccaeac448361518 removes the accuracy from the WebUI as it is currently useless.

**Comment by giuseppetotaro** [comment]
Basically we need to show the statistics on how many high relevant, relevant, and not relevant results have been marked by user with respect to a specific model.

**Comment by giuseppetotaro** [comment]
This is a duplicate of issue #10.
