### ISSUE TITLE
Popup info on the main interface

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/sce-domain-discovery#3]
The following items in the interface should have tooltips added to them:
1. Highly Relevant buttons: "<b>Highly Relevant</b>: This page contains the type of information required to answer questions for this domain. This is exactly what we are looking for.'
2. Relevant buttons: "<b>Relevant</b>: This page contains domain-relevant information, but it won't help answer questions."
3. Not Relevant: "<b>Not Relevant</b>: This page is irrelevant to the domain."

**Comment by giuseppetotaro** [comment]
@wmburke please let me know if you want to extend the tooltips associated with the icons in the header. We could extend each tooltip as you described in this issue.

**Comment by wmburke** [comment]
Yes - this is really important! Please do this!

**Comment by giuseppetotaro** [comment]
Commit 2ac4eb1643bb8e8efc73e34fc8b3a94ffc7bde2b adds the tooltips associated with the icons in the frames. @wmburke please close this issue if it works for you.

**Comment by wmburke** [comment]
Awesome! Thank you!
